export type GuildFeature =
    | 'ACTIVITIES_ALPHA'
    | 'ACTIVITIES_EMPLOYEE'
    | 'ACTIVITIES_INTERNAL_DEV'
    | 'ACTIVITIES_WIP'
    | 'ANIMATED_BANNER'
    | 'ANIMATED_ICON'
    | 'APPLICATION_COMMAND_PERMISSIONS_V2'
    | 'AUTO_MODERATION'
    | 'AUTO_MODERATION_RULE_CREATE_BADGE'
    | 'BANNER'
    | 'BOT_DEVELOPER_EARLY_ACCESS'
    | 'BURST_REACTIONS'
    | 'CHANNEL_ICON_EMOJIS_GENERATED'
    | 'CHANNEL_ICON_EMOJIS_POPSICLE'
    | 'CHANNEL_ICON_EMOJIS_POTATO'
    | 'CHANNEL_ICON_EMOJIS_SUNGLASSES'
    | 'CHANNEL_ICON_EMOJIS_TADA'
    | 'COMMERCE'
    | 'COMMUNITY'
    | 'CREATOR_MONETIZABLE_DISABLED'
    | 'CREATOR_MONETIZABLE_ENABLED'
    | 'CREATOR_STORE_PAGE'
    | 'DEVELOPER_SUPPORT_SERVER'
    | 'DISCOVERABLE'
    | 'FEATURABLE'
    | 'GUILD_HOME_TEST'
    | 'GUILD_ONBOARDING'
    | 'GUILD_ONBOARDING_EVER_ENABLED'
    | 'GUILD_ONBOARDING_HAS_PROMPTS'
    | 'GUILD_PRODUCTS'
    | 'GUILD_ROLE_SUBSCRIPTIONS_AVAILABLE_FOR_PURCHASE'
    | 'GUILD_ROLE_SUBSCRIPTIONS_ENABLED'
    | 'GUILD_WEB_PAGE_VANITY_URL'
    | 'HAD_EARLY_ACTIVITIES_ACCESS'
    | 'HUB'
    | 'INTERNAL_EMPLOYEE_ONLY'
    | 'INTERNAL_NOTIFICATION_SETTINGS'
    | 'INVITES_DISABLED'
    | 'INVITE_SPLASH'
    | 'LINKED_TO_HUB'
    | 'MEMBER_PROFILES'
    | 'MEMBER_VERIFICATION_GATE_ENABLED'
    | 'MORE_STICKERS'
    | 'NEWS'
    | 'NEW_THREAD_PERMISSIONS'
    | 'PARTNERED'
    | 'PREVIEW_ENABLED'
    | 'PRIVATE_THREADS'
    | 'RAID_ALERTS_DISABLED'
    | 'RAID_ALERTS_ENABLED'
    | 'RELAY_ENABLED'
    | 'ROLE_ICONS'
    | 'ROLE_SUBSCRIPTIONS_ENABLED_FOR_PURCHASE'
    | 'SEVEN_DAY_THREAD_ARCHIVE'
    | 'TEXT_IN_VOICE_ENABLED'
    | 'THREAD_DEFAULT_AUTO_ARCHIVE_DURATION'
    | 'THREADS_ENABLED'
    | 'THREADS_ENABLED_TESTING'
    | 'TICKETED_EVENTS_ENABLED'
    | 'VANITY_URL'
    | 'VERIFIED'
    | 'VIP_REGIONS'
    | 'WELCOME_SCREEN_ENABLED';

export const FEATURES: GuildFeature[] = [
    'ACTIVITIES_ALPHA',
    'ACTIVITIES_EMPLOYEE',
    'ACTIVITIES_INTERNAL_DEV',
    'ACTIVITIES_WIP',
    'ANIMATED_BANNER',
    'ANIMATED_ICON',
    'APPLICATION_COMMAND_PERMISSIONS_V2',
    'AUTO_MODERATION',
    'AUTO_MODERATION_RULE_CREATE_BADGE',
    'BANNER',
    'BOT_DEVELOPER_EARLY_ACCESS',
    'BURST_REACTIONS',
    'CHANNEL_ICON_EMOJIS_GENERATED',
    'CHANNEL_ICON_EMOJIS_POPSICLE',
    'CHANNEL_ICON_EMOJIS_POTATO',
    'CHANNEL_ICON_EMOJIS_SUNGLASSES',
    'CHANNEL_ICON_EMOJIS_TADA',
    'COMMERCE',
    'COMMUNITY',
    'CREATOR_MONETIZABLE_DISABLED',
    'CREATOR_MONETIZABLE_ENABLED',
    'CREATOR_STORE_PAGE',
    'DEVELOPER_SUPPORT_SERVER',
    'DISCOVERABLE',
    'FEATURABLE',
    'GUILD_HOME_TEST',
    'GUILD_ONBOARDING',
    'GUILD_ONBOARDING_EVER_ENABLED',
    'GUILD_ONBOARDING_HAS_PROMPTS',
    'GUILD_PRODUCTS',
    'GUILD_ROLE_SUBSCRIPTIONS_AVAILABLE_FOR_PURCHASE',
    'GUILD_ROLE_SUBSCRIPTIONS_ENABLED',
    'GUILD_WEB_PAGE_VANITY_URL',
    'HAD_EARLY_ACTIVITIES_ACCESS',
    'HUB',
    'INTERNAL_EMPLOYEE_ONLY',
    'INTERNAL_NOTIFICATION_SETTINGS',
    'INVITES_DISABLED',
    'INVITE_SPLASH',
    'LINKED_TO_HUB',
    'MEMBER_PROFILES',
    'MEMBER_VERIFICATION_GATE_ENABLED',
    'MORE_STICKERS',
    'NEWS',
    'NEW_THREAD_PERMISSIONS',
    'PARTNERED',
    'PREVIEW_ENABLED',
    'PRIVATE_THREADS',
    'RAID_ALERTS_DISABLED',
    'RAID_ALERTS_ENABLED',
    'RELAY_ENABLED',
    'ROLE_ICONS',
    'ROLE_SUBSCRIPTIONS_ENABLED_FOR_PURCHASE',
    'SEVEN_DAY_THREAD_ARCHIVE',
    'TEXT_IN_VOICE_ENABLED',
    'THREAD_DEFAULT_AUTO_ARCHIVE_DURATION',
    'THREADS_ENABLED',
    'THREADS_ENABLED_TESTING',
    'TICKETED_EVENTS_ENABLED',
    'VANITY_URL',
    'VERIFIED',
    'VIP_REGIONS',
    'WELCOME_SCREEN_ENABLED',
];
